### ISSUE TITLE
model missing BrainModel.h5  and Kidney_Model.h5 file not found

### ISSUE THREAD

**Issue by datacrud8** [KalyanM45/OpenHealth#10]
Already email sent about the below issue :
Can you please send models over the email. Thanks.

However, while opening app.py, this error is encountered:
File "/root/medai/OpenHealth/app.py", line 18, in

brain_model = load_model('Artifacts\Brain_Tumour\BrainModel.h5')
kidney_model = load_model('Artifacts\Kidney_Disease\Kidney_Model.h5')

**Comment by KalyanM45** [comment]
Sending, Thank You

**Comment by KalyanM45** [comment]
Can you please drop me your mail here, I can't find you

**Comment by datacrud8** [comment]
sure I sent email to this ID: kalyanmurapaka274@gmail.com
