### ISSUE TITLE
BrainModel.h5 file not found

### ISSUE THREAD

**Issue by moataz-abbas** [KalyanM45/OpenHealth#9]
Congrates on the good job.

However, while opening app.py, this error is encountered: 
File "/root/medai/OpenHealth/app.py", line 18, in <module>
    brain_model = load_model('Artifacts\Brain_Tumour\BrainModel.h5')

**Comment by KalyanM45** [comment]
Refer: https://github.com/KalyanM45/OpenHealth/discussions/7
